In [30]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
ads = pd.read_csv('E:/Netzwerk/Practice/Social_Network_Ads.csv')

In [4]:
ads.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
ads.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [7]:
#check wheteher the data is balanced or not
ads['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [8]:
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [89]:
#Male = 1 and Female = 0
label_encoder = preprocessing.LabelEncoder()

ads['Gender'] = label_encoder.fit_transform(ads['Gender'])

In [32]:
ads['Gender'] = label_encoder.inverse_transform(ads['Gender'])

In [33]:
ads.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [34]:
X = ads.iloc[:,:-1]

In [35]:
Y = ads.iloc[:,-1]

In [36]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [52]:
#data Normalization to scale the data
X = preprocessing.StandardScaler().fit_transform(X)

In [53]:
X

array([[-0.93657932,  1.02020406, -1.78179743, -1.49004624],
       [ 1.66838653,  1.02020406, -0.25358736, -1.46068138],
       [-0.32087714, -0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.52039175, -0.98019606,  1.17910958, -1.46068138],
       [ 0.88695546,  1.02020406, -0.15807423, -1.07893824],
       [-1.36231017, -0.98019606,  1.08359645, -0.99084367]])

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=1)

In [55]:
Y_test.shape

(80,)

In [68]:
#Training and Predicting

from sklearn.neighbors import KNeighborsClassifier

knnmodel = KNeighborsClassifier(n_neighbors=5)
knnmodel.fit(X_train, Y_train)
ypredict = knnmodel.predict(X_test)

In [69]:
#Accuracy

from sklearn.metrics import accuracy_score

acc = accuracy_score(Y_test,ypredict)

In [70]:
acc

0.875

In [71]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,ypredict)
cm

array([[41,  7],
       [ 3, 29]], dtype=int64)

In [86]:
prediction_output = pd.DataFrame(data = [Y_test.values, ypredict], index=['y_test','ypredict'])

In [88]:
prediction_output.transpose()

y_test  ypredict
0        0         0
1        0         0
2        1         1
3        1         1
4        0         0
..     ...       ...
75       1         1
76       0         0
77       0         0
78       0         0
79       0         0

[80 rows x 2 columns]

In [64]:
ypredict

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)