In [84]:
import pandas as pd
import numpy as np
from scipy import stats as st
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv('E:/Netzwerk/Practice/wine_data.csv')

In [16]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Class, Alcohol, Malic acid, Ash, Alcalinity of ash, Magnesium, Total phenols, Flavanoids, Nonflavanoid phenols, Proanthocyanins, Color intensity, Hue, OD280/OD315, Proline]
Index: []

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
Class                   178 non-null int64
Alcohol                 178 non-null float64
Malic acid              178 non-null float64
Ash                     178 non-null float64
Alcalinity of ash       178 non-null float64
Magnesium               178 non-null int64
Total phenols           178 non-null float64
Flavanoids              178 non-null float64
Nonflavanoid phenols    178 non-null float64
Proanthocyanins         178 non-null float64
Color intensity         178 non-null float64
Hue                     178 non-null float64
OD280/OD315             178 non-null float64
Proline                 178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [18]:
df.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      0    14.23        1.71  2.43               15.6        127   
1      0    13.20        1.78  2.14               11.2        100   
2      0    13.16        2.36  2.67               18.6        101   
3      0    14.37        1.95  2.50               16.8        113   
4      0    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315  Proline  
0             5.64  1.04         3.92     1065  
1             4.38  1.05         3.40     1050  
2             5.68  1.03         3.17     1185  
3             7.80  0.86         3.45     1480  
4             4.32  1.04         2.93      735

In [22]:
z = np.abs(stats.zscore(df))

In [23]:
z

array([[1.21394365, 1.51861254, 0.5622498 , ..., 0.36217728, 1.84791957,
        1.01300893],
       [1.21394365, 0.24628963, 0.49941338, ..., 0.40605066, 1.1134493 ,
        0.96524152],
       [1.21394365, 0.19687903, 0.02123125, ..., 0.31830389, 0.78858745,
        1.39514818],
       ...,
       [1.37386437, 0.33275817, 1.74474449, ..., 1.61212515, 1.48544548,
        0.28057537],
       [1.37386437, 0.20923168, 0.22769377, ..., 1.56825176, 1.40069891,
        0.29649784],
       [1.37386437, 1.39508604, 1.58316512, ..., 1.52437837, 1.42894777,
        0.59516041]])

In [26]:
threshold = 3
print(np.where(z>3))

(array([ 25,  59,  69,  73,  95, 110, 115, 121, 121, 123, 158], dtype=int64), array([ 3,  3,  5,  4,  5,  9, 11,  3,  7,  2, 10], dtype=int64))


In [27]:
z[25][3]

3.1197718608780005

In [29]:
df1 = df[(z<3).all(axis = 1)]

In [31]:
df1.shape

(168, 14)

In [32]:
df.shape

(178, 14)

In [34]:
X = df1.iloc[:,1:]
X.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6        127           2.80   
1    13.20        1.78  2.14               11.2        100           2.65   
2    13.16        2.36  2.67               18.6        101           2.80   
3    14.37        1.95  2.50               16.8        113           3.85   
4    13.24        2.59  2.87               21.0        118           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315  Proline  
0         3.92     1065  
1         3.40     1050  
2         3.17     1185  
3         3.45     1480  
4         2.93      735

In [66]:
y = df1.iloc[:,0]

In [67]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [68]:
#data Normalization

X = preprocessing.StandardScaler().fit_transform(X)
X

array([[ 1.51353876, -0.57884166,  0.25063712, ...,  0.40376609,
         1.8574532 ,  0.98053667],
       [ 0.21092886, -0.51488846, -0.94535119, ...,  0.44924866,
         1.12760518,  0.93341436],
       [ 0.16034207,  0.01500942,  1.24042055, ...,  0.35828352,
         0.80478778,  1.35751513],
       ...,
       [ 0.29945574,  1.76915415, -0.45045947, ..., -1.64294949,
        -1.454934  ,  0.25799463],
       [ 0.17298876,  0.22514134,  0.00319127, ..., -1.59746692,
        -1.37072076,  0.27370207],
       [ 1.38707178,  1.60470308,  1.52910738, ..., -1.55198436,
        -1.39879184, -0.60591433]])

In [69]:
knn = KNeighborsClassifier()

In [70]:
k_range = list(range(1,31))
weight_options = ['uniform','distance']
metric_k = ["euclidean",'manhattan']

param_grid = dict(n_neighbors = k_range, weights = weight_options, metric = metric_k)

In [71]:
grid = GridSearchCV(knn, param_grid, cv = 8, verbose = 1, n_jobs = -1)
grid.fit(X,y)

Fitting 8 folds for each of 120 candidates, totalling 960 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    4.4s
[Parallel(n_jobs=-1)]: Done 960 out of 960 | elapsed:    5.3s finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=8, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [72]:
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

0.9880952380952381
{'metric': 'euclidean', 'n_neighbors': 29, 'weights': 'uniform'}
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=29, p=2,
                     weights='uniform')


In [73]:
#Train Test split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=1)

In [81]:
#Training and Predicting

knn = KNeighborsClassifier(n_neighbors = 29)
knn.fit(X_train, y_train)
ypredict = knn.predict(X_test)

In [82]:
# Accuracy

acc = accuracy_score(y_test, ypredict)
acc

1.0

In [85]:
#Confusion Matrix

cm = confusion_matrix(y_test, ypredict)
cm

array([[14,  0,  0],
       [ 0, 11,  0],
       [ 0,  0,  9]], dtype=int64)

In [86]:
pwd

'C:\\Users\\akshat.vijayvergia'